/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Source.Taller;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author JDiaz
 */
public class LoginSecretario extends javax.swing.JInternalFrame {

    private Taller taller;
    public LoginSecretario(Taller taller) throws Exception {
        initComponents();
        usuario.addActionListener(new AccesoListener());
        entrar.addActionListener(new AccesoListener());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        entrar = new javax.swing.JButton();
        jlabel2 = new javax.swing.JLabel();
        pass = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setVisible(false);

        jPanel1.setEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Usuario:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 106, 22));
        jPanel1.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 179, -1));

        entrar.setText("Entrar");
        jPanel1.add(entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, -1, -1));

        jlabel2.setText("Contraseña:");
        jPanel1.add(jlabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 106, 22));
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 179, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login_Secretario.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton entrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlabel2;
    private javax.swing.JTextField pass;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables

    
    public class AccesoListener implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent ae) {
            
            try {
                taller.buscarGerente("jdiaz93").getCorreo();
            } catch (Exception ex) {
                Logger.getLogger(LoginSecretario.class.getName()).log(Level.SEVERE, null, ex);
            }


            
        }
        
    }

}
