/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Source.Gerente;
import Source.Report;
import Source.Secretario;
import Source.Taller;
import Source.TipoCargo;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import rojerusan.RSAnimation;

/**
 *
 * @author julia
 */
public class MainWindow extends javax.swing.JFrame {

    private Taller taller;
    private Secretario secretario;
    private Report reporte;
    private int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
    private int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;

    public MainWindow(Taller taller) {

        this.taller = taller;
        this.secretario = secretario;
        this.reporte = reporte;

        initComponents();

        btnlogOut.setVisible(false);

        IngresoVehiculoListener ingresoVeh = new IngresoVehiculoListener();
        AsignacionMecanicoListener asigMeca = new AsignacionMecanicoListener();

        this.IngresodeVehiculo.addActionListener(ingresoVeh);
        this.asignacionMecanico.addActionListener(asigMeca);
        this.registroProductos.addActionListener(new RegistroProductosListener());
        this.facturacionSrevicio.addActionListener(new FacturacionListener());

        this.btnIngresodeVehiculo.addActionListener(ingresoVeh);
        this.btnAsigMecanico.addActionListener(asigMeca);

        this.acerca.addActionListener(new AboutUIListener());

        OcultarMostrarJPanel("ocultar");

        usuarioGerente.addActionListener(new AccesoGerente());
        usuarioSecretario.addActionListener(new AccesoSecretario());

        passGerente.addActionListener(new AccesoGerente());
        passSecretario.addActionListener(new AccesoSecretario());

        this.entrarGerente.addActionListener(new AccesoGerente());
        this.entrarSecretario.addActionListener(new AccesoSecretario());
        
        this.regProducto.addActionListener(new RegistroProductoListener());

//        Login loginWindow = new Login(taller);
//        jDesktopPane1.add(loginWindow);
//        loginWindow.setVisible(true);
//        loginWindow.setEnabled(false);


        btnlogOut.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                
                secretario = null;
                nombreSession.setVisible(false);
                btnlogOut.setVisible(false);
                btnSecretario.setVisible(true);
                btnGerente.setVisible(true);
                jlabel.setVisible(true);
                jlabel2.setVisible(true);
                
                ActivarDesactivarComponenetes("no");
            }
        });
        
        

    }
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnRegistroServicios = new javax.swing.JButton();
        btnFacturacionServicio = new javax.swing.JButton();
        btnRegistrodeProductos = new javax.swing.JButton();
        btnAsigMecanico = new javax.swing.JButton();
        btnIngresodeVehiculo = new javax.swing.JButton();
        btnFacturacionServicio1 = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        jpanel_mesa = new javax.swing.JPanel();
        btnlogOut = new javax.swing.JButton();
        btnSecretario = new javax.swing.JButton();
        jlabel = new javax.swing.JLabel();
        jlabel2 = new javax.swing.JLabel();
        btnGerente = new javax.swing.JButton();
        nombreSession = new javax.swing.JLabel();
        jPanelSecretario = new javax.swing.JPanel();
        entrarSecretario = new javax.swing.JButton();
        jButtonClose2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        usuarioSecretario = new javax.swing.JTextField();
        jlabel3 = new javax.swing.JLabel();
        passSecretario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanelGerente = new javax.swing.JPanel();
        jButtonClose = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        usuarioGerente = new javax.swing.JTextField();
        entrarGerente = new javax.swing.JButton();
        jlabel4 = new javax.swing.JLabel();
        passGerente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuSolicitudes = new javax.swing.JMenu();
        IngresodeVehiculo = new javax.swing.JMenuItem();
        jMenuMantenimiento = new javax.swing.JMenu();
        asignacionMecanico = new javax.swing.JMenuItem();
        jMenuFacturacion = new javax.swing.JMenu();
        registroProductos = new javax.swing.JMenuItem();
        facturacionSrevicio = new javax.swing.JMenuItem();
        jMenuRegistros = new javax.swing.JMenu();
        regProducto = new javax.swing.JMenuItem();
        regServicio = new javax.swing.JMenuItem();
        regMeacanico = new javax.swing.JMenuItem();
        regSecretarioInv = new javax.swing.JMenuItem();
        regSecretarioIng = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        acerca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane1.setBackground(new java.awt.Color(102, 102, 102));
        jDesktopPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setEnabled(false);

        btnRegistroServicios.setText("Registro de Servicio");
        btnRegistroServicios.setBorderPainted(false);
        btnRegistroServicios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistroServicios.setEnabled(false);
        btnRegistroServicios.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);

        btnFacturacionServicio.setText("Registro Productos Utilizados");
        btnFacturacionServicio.setBorderPainted(false);
        btnFacturacionServicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFacturacionServicio.setEnabled(false);
        btnFacturacionServicio.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);

        btnRegistrodeProductos.setText("Registro de Producto      ");
        btnRegistrodeProductos.setBorderPainted(false);
        btnRegistrodeProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrodeProductos.setEnabled(false);
        btnRegistrodeProductos.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnRegistrodeProductos.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        btnAsigMecanico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AsigMecanico.png"))); // NOI18N
        btnAsigMecanico.setText("Asignar Mecanico         ");
        btnAsigMecanico.setBorderPainted(false);
        btnAsigMecanico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAsigMecanico.setEnabled(false);
        btnAsigMecanico.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnAsigMecanico.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnAsigMecanico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAsigMecanicoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAsigMecanicoMouseExited(evt);
            }
        });

        btnIngresodeVehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ingresoVeh.png"))); // NOI18N
        btnIngresodeVehiculo.setText("Ingreso de vehiculo       ");
        btnIngresodeVehiculo.setAutoscrolls(true);
        btnIngresodeVehiculo.setBorderPainted(false);
        btnIngresodeVehiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresodeVehiculo.setEnabled(false);
        btnIngresodeVehiculo.setFocusPainted(false);
        btnIngresodeVehiculo.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnIngresodeVehiculo.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnIngresodeVehiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIngresodeVehiculoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIngresodeVehiculoMouseExited(evt);
            }
        });

        btnFacturacionServicio1.setText("Facturacion del Servicio");
        btnFacturacionServicio1.setBorderPainted(false);
        btnFacturacionServicio1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFacturacionServicio1.setEnabled(false);
        btnFacturacionServicio1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFacturacionServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFacturacionServicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistroServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIngresodeVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAsigMecanico, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrodeProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnIngresodeVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnAsigMecanico, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnFacturacionServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnFacturacionServicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnRegistrodeProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnRegistroServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(246, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 700));
        jPanel1.getAccessibleContext().setAccessibleParent(jPanel1);

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu.png"))); // NOI18N
        btnMenu.setBorderPainted(false);
        btnMenu.setContentAreaFilled(false);
        btnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        jPanel4.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 50, 50));

        jpanel_mesa.setLayout(null);

        btnlogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout100px.png"))); // NOI18N
        btnlogOut.setAlignmentX(0.5F);
        btnlogOut.setBorderPainted(false);
        btnlogOut.setContentAreaFilled(false);
        btnlogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlogOut.setFocusPainted(false);
        btnlogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogOutActionPerformed(evt);
            }
        });
        jpanel_mesa.add(btnlogOut);
        btnlogOut.setBounds(820, 0, 104, 31);

        btnSecretario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logoSecretario.png"))); // NOI18N
        btnSecretario.setBorderPainted(false);
        btnSecretario.setContentAreaFilled(false);
        btnSecretario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSecretario.setFocusPainted(false);
        btnSecretario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSecretarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSecretarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSecretarioMouseExited(evt);
            }
        });
        jpanel_mesa.add(btnSecretario);
        btnSecretario.setBounds(560, 212, 202, 188);

        jlabel.setBackground(new java.awt.Color(102, 102, 102));
        jlabel.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jlabel.setForeground(new java.awt.Color(255, 255, 255));
        jlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabel.setText("Gerente");
        jlabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlabel.setOpaque(true);
        jpanel_mesa.add(jlabel);
        jlabel.setBounds(220, 412, 202, 27);

        jlabel2.setBackground(new java.awt.Color(102, 102, 102));
        jlabel2.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jlabel2.setForeground(new java.awt.Color(255, 255, 255));
        jlabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabel2.setText("Secretario");
        jlabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlabel2.setOpaque(true);
        jpanel_mesa.add(jlabel2);
        jlabel2.setBounds(560, 412, 202, 27);

        btnGerente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logoGerente.png"))); // NOI18N
        btnGerente.setBorderPainted(false);
        btnGerente.setContentAreaFilled(false);
        btnGerente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGerente.setFocusPainted(false);
        btnGerente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGerente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGerenteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGerenteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGerenteMouseExited(evt);
            }
        });
        jpanel_mesa.add(btnGerente);
        btnGerente.setBounds(220, 216, 203, 188);

        nombreSession.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nombreSession.setEnabled(false);
        jpanel_mesa.add(nombreSession);
        nombreSession.setBounds(380, 0, 432, 31);

        jPanelSecretario.setEnabled(false);
        jPanelSecretario.setPreferredSize(new java.awt.Dimension(780, 281));
        jPanelSecretario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        entrarSecretario.setText("Entrar");
        entrarSecretario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelSecretario.add(entrarSecretario, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 300, -1));

        jButtonClose2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Button_close.png"))); // NOI18N
        jButtonClose2.setBorderPainted(false);
        jButtonClose2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonClose2.setFocusPainted(false);
        jButtonClose2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonClose2MouseClicked(evt);
            }
        });
        jPanelSecretario.add(jButtonClose2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        jLabel1.setText("Usuario:");
        jPanelSecretario.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 106, 22));
        jPanelSecretario.add(usuarioSecretario, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 179, -1));

        jlabel3.setText("Contraseña:");
        jPanelSecretario.add(jlabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 106, 22));
        jPanelSecretario.add(passSecretario, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 179, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login_Gerente.png"))); // NOI18N
        jPanelSecretario.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 780, -1));

        jpanel_mesa.add(jPanelSecretario);
        jPanelSecretario.setBounds(95, 200, 780, 280);

        jPanelGerente.setEnabled(false);
        jPanelGerente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Button_close.png"))); // NOI18N
        jButtonClose.setBorderPainted(false);
        jButtonClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonClose.setFocusPainted(false);
        jButtonClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCloseMouseClicked(evt);
            }
        });
        jPanelGerente.add(jButtonClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        jLabel3.setText("Usuario:");
        jPanelGerente.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 106, 22));
        jPanelGerente.add(usuarioGerente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 179, -1));

        entrarGerente.setText("Entrar");
        entrarGerente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelGerente.add(entrarGerente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, -1, -1));

        jlabel4.setText("Contraseña:");
        jPanelGerente.add(jlabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 106, 22));
        jPanelGerente.add(passGerente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 179, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login_Secretario.png"))); // NOI18N
        jPanelGerente.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 780, -1));

        jpanel_mesa.add(jPanelGerente);
        jPanelGerente.setBounds(95, 200, 780, 281);

        jPanel4.add(jpanel_mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 960, 700));

        jDesktopPane1.setLayer(jPanel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenuBar1.setPreferredSize(new java.awt.Dimension(1200, 26));

        jMenuSolicitudes.setText("Solicitudes");
        jMenuSolicitudes.setEnabled(false);
        jMenuSolicitudes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        IngresodeVehiculo.setText("Ingreso de vehiculos");
        jMenuSolicitudes.add(IngresodeVehiculo);

        jMenuBar1.add(jMenuSolicitudes);

        jMenuMantenimiento.setText("Mantenimiento");
        jMenuMantenimiento.setEnabled(false);
        jMenuMantenimiento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        asignacionMecanico.setText("Asignacion de Mecanico");
        jMenuMantenimiento.add(asignacionMecanico);

        jMenuBar1.add(jMenuMantenimiento);

        jMenuFacturacion.setText("Facturacion");
        jMenuFacturacion.setEnabled(false);
        jMenuFacturacion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        registroProductos.setText("Registro de productos utilizados");
        registroProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroProductosActionPerformed(evt);
            }
        });
        jMenuFacturacion.add(registroProductos);

        facturacionSrevicio.setText("Facturacion del Servicio");
        jMenuFacturacion.add(facturacionSrevicio);

        jMenuBar1.add(jMenuFacturacion);

        jMenuRegistros.setText("Registros");
        jMenuRegistros.setEnabled(false);
        jMenuRegistros.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        regProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logoProducto.png"))); // NOI18N
        regProducto.setText("Registro de Producto");
        regProducto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenuRegistros.add(regProducto);

        regServicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logoServicio.png"))); // NOI18N
        regServicio.setText("Registro de Servicio");
        jMenuRegistros.add(regServicio);

        regMeacanico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logoMecanico.png"))); // NOI18N
        regMeacanico.setText("Registro de Mecanico");
        regMeacanico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regMeacanicoActionPerformed(evt);
            }
        });
        jMenuRegistros.add(regMeacanico);

        regSecretarioInv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logoSecInv.png"))); // NOI18N
        regSecretarioInv.setText("Registro de Sercretario de inventario");
        jMenuRegistros.add(regSecretarioInv);

        regSecretarioIng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logoSecreIngresos.png"))); // NOI18N
        regSecretarioIng.setText("Registro de Secretario de ingresos");
        jMenuRegistros.add(regSecretarioIng);

        jMenuBar1.add(jMenuRegistros);

        jMenu4.setText("Ayuda");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        acerca.setText("Acerca de");
        jMenu4.add(acerca);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registroProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registroProductosActionPerformed

    private void regMeacanicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regMeacanicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regMeacanicoActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed

        int posicion = btnMenu.getX();
        if (posicion > 5) {
            RSAnimation.setMoverIzquierda(279, 0, 2, 2, btnMenu);
            RSAnimation.setMoverIzquierda(5, -280, 2, 2, jPanel1);

        } else {
            RSAnimation.setMoverDerecha(5, 270, 2, 2, btnMenu);
            RSAnimation.setMoverDerecha(-270, 0, 2, 2, jPanel1);
        }
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnIngresodeVehiculoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresodeVehiculoMouseExited
        btnIngresodeVehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ingresoVeh.png")));
    }//GEN-LAST:event_btnIngresodeVehiculoMouseExited

    private void btnIngresodeVehiculoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresodeVehiculoMouseEntered

        btnIngresodeVehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ingresoVehON.png")));
    }//GEN-LAST:event_btnIngresodeVehiculoMouseEntered

    private void btnAsigMecanicoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAsigMecanicoMouseExited
        btnAsigMecanico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AsigMecanico.png")));
    }//GEN-LAST:event_btnAsigMecanicoMouseExited

    private void btnAsigMecanicoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAsigMecanicoMouseEntered
        btnAsigMecanico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AsigMecanicoON.png")));
    }//GEN-LAST:event_btnAsigMecanicoMouseEntered

    private void btnGerenteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGerenteMouseEntered
        btnGerente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gerenteAumento.png")));
    }//GEN-LAST:event_btnGerenteMouseEntered

    private void btnGerenteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGerenteMouseExited
        btnGerente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logoGerente.png")));
    }//GEN-LAST:event_btnGerenteMouseExited

    private void btnSecretarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSecretarioMouseEntered
        btnSecretario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SecretarioAumento.png")));
    }//GEN-LAST:event_btnSecretarioMouseEntered

    private void btnSecretarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSecretarioMouseExited
        btnSecretario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logoSecretario.png")));
    }//GEN-LAST:event_btnSecretarioMouseExited

    private void btnGerenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGerenteMouseClicked
        OcultarMostrarJPanel("ocultar");
        jPanelGerente.setVisible(true);

        btnGerente.setVisible(false);
        btnSecretario.setVisible(false);

        jlabel.setVisible(false);
        jlabel2.setVisible(false);
    }//GEN-LAST:event_btnGerenteMouseClicked

    private void jButtonCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCloseMouseClicked
        jPanelGerente.setVisible(false);

        btnGerente.setVisible(true);
        btnSecretario.setVisible(true);

        jlabel.setVisible(true);
        jlabel2.setVisible(true);
    }//GEN-LAST:event_jButtonCloseMouseClicked

    private void btnSecretarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSecretarioMouseClicked
        OcultarMostrarJPanel("ocultar");
        jPanelSecretario.setVisible(true);

        btnGerente.setVisible(false);
        btnSecretario.setVisible(false);

        jlabel.setVisible(false);
        jlabel2.setVisible(false);
    }//GEN-LAST:event_btnSecretarioMouseClicked

    private void jButtonClose2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonClose2MouseClicked

        jPanelSecretario.setVisible(false);

        btnGerente.setVisible(true);
        btnSecretario.setVisible(true);

        jlabel.setVisible(true);
        jlabel2.setVisible(true);
    }//GEN-LAST:event_jButtonClose2MouseClicked

    private void btnlogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlogOutActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem IngresodeVehiculo;
    private javax.swing.JMenuItem acerca;
    private javax.swing.JMenuItem asignacionMecanico;
    private javax.swing.JButton btnAsigMecanico;
    private javax.swing.JButton btnFacturacionServicio;
    private javax.swing.JButton btnFacturacionServicio1;
    private javax.swing.JButton btnGerente;
    private javax.swing.JButton btnIngresodeVehiculo;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnRegistroServicios;
    private javax.swing.JButton btnRegistrodeProductos;
    private javax.swing.JButton btnSecretario;
    private javax.swing.JButton btnlogOut;
    private javax.swing.JButton entrarGerente;
    private javax.swing.JButton entrarSecretario;
    private javax.swing.JMenuItem facturacionSrevicio;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonClose2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFacturacion;
    private javax.swing.JMenu jMenuMantenimiento;
    private javax.swing.JMenu jMenuRegistros;
    private javax.swing.JMenu jMenuSolicitudes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelGerente;
    private javax.swing.JPanel jPanelSecretario;
    private javax.swing.JLabel jlabel;
    private javax.swing.JLabel jlabel2;
    private javax.swing.JLabel jlabel3;
    private javax.swing.JLabel jlabel4;
    private javax.swing.JPanel jpanel_mesa;
    private javax.swing.JLabel nombreSession;
    private javax.swing.JTextField passGerente;
    private javax.swing.JTextField passSecretario;
    private javax.swing.JMenuItem regMeacanico;
    private javax.swing.JMenuItem regProducto;
    private javax.swing.JMenuItem regSecretarioIng;
    private javax.swing.JMenuItem regSecretarioInv;
    private javax.swing.JMenuItem regServicio;
    private javax.swing.JMenuItem registroProductos;
    private javax.swing.JTextField usuarioGerente;
    private javax.swing.JTextField usuarioSecretario;
    // End of variables declaration//GEN-END:variables

    public class IngresoVehiculoListener implements ActionListener {

        private IngresoVehiculosUI ingresoVH = null;

        public void actionPerformed(ActionEvent evt) {

            if (this.ingresoVH == null) {
                try {

                    ingresoVH = new IngresoVehiculosUI(taller, secretario, reporte);

                } catch (Exception ex) {
                    Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
                jDesktopPane1.add(ingresoVH);
            }

            this.ingresoVH.setLocation(((jDesktopPane1.getWidth() - ingresoVH.getWidth()) / 2) + 140,
                    ((jDesktopPane1.getHeight() - ingresoVH.getHeight()) / 2) + 10);
            ingresoVH.setVisible(true);
        }
    }

    public class AsignacionMecanicoListener implements ActionListener {

        private AsignacionMecanicoUI asignacion = null;

        public void actionPerformed(ActionEvent evt) {

            if (this.asignacion == null) {
                try {

                    asignacion = new AsignacionMecanicoUI(taller);

                } catch (Exception ex) {
                    Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
                jDesktopPane1.add(asignacion);
            }
            this.asignacion.setLocation(((jDesktopPane1.getWidth() - asignacion.getWidth()) / 2),
                    (jDesktopPane1.getHeight() - asignacion.getHeight()) / 2);
            asignacion.setVisible(true);
            RSAnimation.setMoverIzquierda(279, 0, 2, 2, btnMenu);
            RSAnimation.setMoverIzquierda(5, -280, 2, 2, jPanel1);

        }
    }

    public class RegistroProductosListener implements ActionListener {

        private RegistroProductosUtilizadosUI registroPro = null;

        public void actionPerformed(ActionEvent evt) {

            if (this.registroPro == null) {
                try {
                    registroPro = new RegistroProductosUtilizadosUI(taller);
                } catch (Exception ex) {
                    Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
                jDesktopPane1.add(registroPro);
            }

            this.registroPro.setLocation(((jDesktopPane1.getWidth() - this.registroPro.getWidth()) / 2) + 120,
                    (jDesktopPane1.getHeight() - this.registroPro.getHeight()) / 2);
            registroPro.setVisible(true);

        }
    }

    public class FacturacionListener implements ActionListener {

        private FacturacionServicioUI facturacion = null;

        public void actionPerformed(ActionEvent evt) {

            if (this.facturacion == null) {
                try {
                    facturacion = new FacturacionServicioUI(taller,secretario);
                } catch (Exception ex) {
                    Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
                jDesktopPane1.add(facturacion);
            }

            this.facturacion.setLocation(((jDesktopPane1.getWidth() - this.facturacion.getWidth()) / 2) + 120,
                    (jDesktopPane1.getHeight() - this.facturacion.getHeight()) / 2);
            this.facturacion.setVisible(true);

        }
    }

    public class AboutUIListener implements ActionListener {

        private AboutUI about = null;

        @Override
        public void actionPerformed(ActionEvent ae) {

            if (this.about == null) {
                this.about = new AboutUI();
                jDesktopPane1.add(this.about);
                this.about.setLocation(85, 30);
            }
            this.about.setLocation(360,520);
            this.about.setVisible(true);
        }

    }

    public class LoginGerenteListener implements ActionListener {

        private LoginGerente login = null;

        @Override
        public void actionPerformed(ActionEvent ae) {

            if (this.login == null) {

                try {
                    this.login = new LoginGerente(taller);
                } catch (Exception ex) {
                    Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
                jDesktopPane1.add(this.login);

            }
            this.login.setLocation((jDesktopPane1.getWidth() - this.login.getWidth()) / 2,
                    (jDesktopPane1.getHeight() - this.login.getHeight()) / 2);
            this.login.setVisible(true);

            RSAnimation.setMoverIzquierda(279, 0, 2, 2, btnMenu);
            RSAnimation.setMoverIzquierda(5, -280, 2, 2, jPanel1);

        }

    }

    public class LoginSecretarioListener implements ActionListener {

        private LoginSecretario login = null;

        @Override
        public void actionPerformed(ActionEvent ae) {

            if (this.login == null) {

                try {
                    this.login = new LoginSecretario(taller);
                } catch (Exception ex) {
                    Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
                jDesktopPane1.add(this.login);

            }
            this.login.setLocation((jDesktopPane1.getWidth() - this.login.getWidth()) / 2,
                    (jDesktopPane1.getHeight() - this.login.getHeight()) / 2);
            this.login.setVisible(true);

            RSAnimation.setMoverIzquierda(279, 0, 2, 2, btnMenu);
            RSAnimation.setMoverIzquierda(5, -280, 2, 2, jPanel1);

        }

    }

    public void OcultarMostrarJPanel(String opcion) {
        if (opcion.equals("mostrar")) {
            jPanelSecretario.setVisible(true);
            jPanelGerente.setVisible(true);
        } else if (opcion.equals("ocultar")) {
            jPanelSecretario.setVisible(false);
            jPanelGerente.setVisible(false);
        }
    }

    public class AccesoGerente implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent ae) {

            for (Gerente g : taller.getGerentes()) {
                if (usuarioGerente.getText().trim().equals(g.getUsuario()) && passGerente.getText().trim().equals(g.getPassword())) {
                    
                    usuarioGerente.setText("");
                    passGerente.setText("");
                    
                    OcultarMostrarJPanel("ocultar");
                    nombreSession.setText("Gerente: " + g.getNombres() + g.getApellidos());
                    btnlogOut.setVisible(true);
                    nombreSession.setVisible(true);
                    ActivarDesactivarComponenetes("si");
                    
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Usuario o contraseña incorrectas.");
                }
            }

        }

    }

    public class AccesoSecretario implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent ae) {

            try {
                
                secretario = taller.buscarSecretario(usuarioSecretario.getText().trim());

                if (secretario.getUsuario().equals(usuarioSecretario.getText())
                        && secretario.getPassword().equals(passSecretario.getText())
                        && secretario.getTipoDeCargo() == TipoCargo.Inventario) {
                    
                    usuarioSecretario.setText("");
                    passSecretario.setText("");

                    OcultarMostrarJPanel("ocultar");
                    nombreSession.setText("Secretario(a) de inventario: " + secretario.getNombres()
                            + " " + secretario.getApellidos());

                    btnRegistroServicios.setEnabled(true);
                    btnRegistrodeProductos.setEnabled(true);

                    jMenuRegistros.setEnabled(true);
                    nombreSession.setVisible(true);
                    btnlogOut.setVisible(true);

                }

                if (secretario.getUsuario().equals(usuarioSecretario.getText())
                        && secretario.getPassword().equals(passSecretario.getText())
                        && secretario.getTipoDeCargo() == TipoCargo.Ingresos) {
                    
                    usuarioSecretario.setText("");
                    passSecretario.setText("");

                    OcultarMostrarJPanel("ocultar");
                    nombreSession.setText("Secretario(a) de ingresos: " + secretario.getNombres()
                            + " " + secretario.getApellidos());

                    btnIngresodeVehiculo.setEnabled(true);
                    btnAsigMecanico.setEnabled(true);
                    btnFacturacionServicio.setEnabled(true);

                    jMenuSolicitudes.setEnabled(true);
                    jMenuMantenimiento.setEnabled(true);
                    jMenuFacturacion.setEnabled(true);

                    
                    nombreSession.setVisible(true);
                    btnlogOut.setVisible(true);

                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            }
        }
    }

    public void ActivarDesactivarComponenetes(String opcion) {

        if (opcion.equals("si")) {
            btnIngresodeVehiculo.setEnabled(true);
            btnAsigMecanico.setEnabled(true);
            btnFacturacionServicio.setEnabled(true);
            btnRegistrodeProductos.setEnabled(true);
            btnRegistroServicios.setEnabled(true);

            jMenuSolicitudes.setEnabled(true);
            jMenuMantenimiento.setEnabled(true);
            jMenuFacturacion.setEnabled(true);
            jMenuRegistros.setEnabled(true);

        } else if (opcion.equals("no")) {

            btnIngresodeVehiculo.setEnabled(false);
            btnAsigMecanico.setEnabled(false);
            btnFacturacionServicio.setEnabled(false);
            btnRegistrodeProductos.setEnabled(false);
            btnRegistroServicios.setEnabled(false);

            jMenuSolicitudes.setEnabled(false);
            jMenuMantenimiento.setEnabled(false);
            jMenuFacturacion.setEnabled(false);
            jMenuRegistros.setEnabled(false);

        }

    }
    
    
    public class RegistroProductoListener implements ActionListener {

        private RegistroProducto registroP = null;

        public void actionPerformed(ActionEvent evt) {

            if (this.registroP == null) {
                try {
                    registroP = new RegistroProducto(taller);
                } catch (Exception ex) {
                    Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
                jDesktopPane1.add(registroP);
            }

            this.registroP.setLocation(((jDesktopPane1.getWidth() - this.registroP.getWidth()) / 2) + 120,
                    (jDesktopPane1.getHeight() - this.registroP.getHeight()) / 2);
            this.registroP.setVisible(true);

        }
    }
    
    
    

}

